name: todo_application
description: "A Project to idez digital"
publish_to: 'Rivaldo Pedro'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^3.4.1+1
  uuid: ^3.0.5
  google_fonts: ^6.1.0
  flutter_slidable: ^3.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.1
  

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  mocktail: ^1.0.1

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
